naming:
  PackageNaming:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    packagePattern: '[A-Za-z][_A-Za-z0-9-]*'

style:
  MagicNumber:
    active: false